// Code generated by MockGen. DO NOT EDIT.
// Source: controller.go
//
// Generated by this command:
//
//	mockgen -source=controller.go -destination=kafkaxtest/controller_mock.go -package=kafkaxtest
//

// Package kafkaxtest is a generated GoMock package.
package kafkaxtest

import (
	reflect "reflect"

	kafkax "github.com/bosonicalcom/bedrock-go/streaming/kafkax"
	gomock "go.uber.org/mock/gomock"
)

// MockController is a mock of Controller interface.
type MockController struct {
	ctrl     *gomock.Controller
	recorder *MockControllerMockRecorder
	isgomock struct{}
}

// MockControllerMockRecorder is the mock recorder for MockController.
type MockControllerMockRecorder struct {
	mock *MockController
}

// NewMockController creates a new mock instance.
func NewMockController(ctrl *gomock.Controller) *MockController {
	mock := &MockController{ctrl: ctrl}
	mock.recorder = &MockControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockController) EXPECT() *MockControllerMockRecorder {
	return m.recorder
}

// RegisterConsumers mocks base method.
func (m *MockController) RegisterConsumers(registrar kafkax.ConsumerRegistrar) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterConsumers", registrar)
}

// RegisterConsumers indicates an expected call of RegisterConsumers.
func (mr *MockControllerMockRecorder) RegisterConsumers(registrar any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterConsumers", reflect.TypeOf((*MockController)(nil).RegisterConsumers), registrar)
}
