// Code generated by MockGen. DO NOT EDIT.
// Source: controller.go
//
// Generated by this command:
//
//	mockgen -source=controller.go -destination=httpxtest/controller_mock.go -package=httpxtest
//

// Package httpxtest is a generated GoMock package.
package httpxtest

import (
	http "net/http"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockController is a mock of Controller interface.
type MockController struct {
	ctrl     *gomock.Controller
	recorder *MockControllerMockRecorder
	isgomock struct{}
}

// MockControllerMockRecorder is the mock recorder for MockController.
type MockControllerMockRecorder struct {
	mock *MockController
}

// NewMockController creates a new mock instance.
func NewMockController(ctrl *gomock.Controller) *MockController {
	mock := &MockController{ctrl: ctrl}
	mock.recorder = &MockControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockController) EXPECT() *MockControllerMockRecorder {
	return m.recorder
}

// RegisterEndpoints mocks base method.
func (m *MockController) RegisterEndpoints(router *http.ServeMux) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterEndpoints", router)
}

// RegisterEndpoints indicates an expected call of RegisterEndpoints.
func (mr *MockControllerMockRecorder) RegisterEndpoints(router any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterEndpoints", reflect.TypeOf((*MockController)(nil).RegisterEndpoints), router)
}
