// Code generated by MockGen. DO NOT EDIT.
// Source: controller.go
//
// Generated by this command:
//
//	mockgen -source=controller.go -destination=grpcxtest/controller_mock.go -package=grpcxtest
//

// Package grpcxtest is a generated GoMock package.
package grpcxtest

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockController is a mock of Controller interface.
type MockController struct {
	ctrl     *gomock.Controller
	recorder *MockControllerMockRecorder
	isgomock struct{}
}

// MockControllerMockRecorder is the mock recorder for MockController.
type MockControllerMockRecorder struct {
	mock *MockController
}

// NewMockController creates a new mock instance.
func NewMockController(ctrl *gomock.Controller) *MockController {
	mock := &MockController{ctrl: ctrl}
	mock.recorder = &MockControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockController) EXPECT() *MockControllerMockRecorder {
	return m.recorder
}

// RegisterServers mocks base method.
func (m *MockController) RegisterServers(registrar grpc.ServiceRegistrar) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterServers", registrar)
}

// RegisterServers indicates an expected call of RegisterServers.
func (mr *MockControllerMockRecorder) RegisterServers(registrar any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterServers", reflect.TypeOf((*MockController)(nil).RegisterServers), registrar)
}
