// Code generated by MockGen. DO NOT EDIT.
// Source: registrar.go
//
// Generated by this command:
//
//	mockgen -source=registrar.go -destination=kafkatest/registrar_mock.go -package=kafkatest
//

// Package kafkatest is a generated GoMock package.
package kafkatest

import (
	reflect "reflect"

	kafkax "github.com/bosonicalcom/bedrock-go/streaming/kafkax"
	gomock "go.uber.org/mock/gomock"
)

// MockConsumerRegistrar is a mock of ConsumerRegistrar interface.
type MockConsumerRegistrar struct {
	ctrl     *gomock.Controller
	recorder *MockConsumerRegistrarMockRecorder
	isgomock struct{}
}

// MockConsumerRegistrarMockRecorder is the mock recorder for MockConsumerRegistrar.
type MockConsumerRegistrarMockRecorder struct {
	mock *MockConsumerRegistrar
}

// NewMockConsumerRegistrar creates a new mock instance.
func NewMockConsumerRegistrar(ctrl *gomock.Controller) *MockConsumerRegistrar {
	mock := &MockConsumerRegistrar{ctrl: ctrl}
	mock.recorder = &MockConsumerRegistrarMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConsumerRegistrar) EXPECT() *MockConsumerRegistrarMockRecorder {
	return m.recorder
}

// Register mocks base method.
func (m *MockConsumerRegistrar) Register(topic string, handler kafkax.Handler, opts ...kafkax.ConsumerRegistrarOption) {
	m.ctrl.T.Helper()
	varargs := []any{topic, handler}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Register", varargs...)
}

// Register indicates an expected call of Register.
func (mr *MockConsumerRegistrarMockRecorder) Register(topic, handler any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{topic, handler}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockConsumerRegistrar)(nil).Register), varargs...)
}
