// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=persistencetest/repository_mock.go -package=persistencetest
//

// Package persistencetest is a generated GoMock package.
package persistencetest

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository[K comparable, T any] struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder[K, T]
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder[K comparable, T any] struct {
	mock *MockRepository[K, T]
}

// NewMockRepository creates a new mock instance.
func NewMockRepository[K comparable, T any](ctrl *gomock.Controller) *MockRepository[K, T] {
	mock := &MockRepository[K, T]{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder[K, T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository[K, T]) EXPECT() *MockRepositoryMockRecorder[K, T] {
	return m.recorder
}

// Delete mocks base method.
func (m *MockRepository[K, T]) Delete(ctx context.Context, v *T) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, v)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRepositoryMockRecorder[K, T]) Delete(ctx, v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRepository[K, T])(nil).Delete), ctx, v)
}

// DeleteByKey mocks base method.
func (m *MockRepository[K, T]) DeleteByKey(ctx context.Context, key K) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByKey", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByKey indicates an expected call of DeleteByKey.
func (mr *MockRepositoryMockRecorder[K, T]) DeleteByKey(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByKey", reflect.TypeOf((*MockRepository[K, T])(nil).DeleteByKey), ctx, key)
}

// GetByKey mocks base method.
func (m *MockRepository[K, T]) GetByKey(ctx context.Context, key K) (*T, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByKey", ctx, key)
	ret0, _ := ret[0].(*T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByKey indicates an expected call of GetByKey.
func (mr *MockRepositoryMockRecorder[K, T]) GetByKey(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByKey", reflect.TypeOf((*MockRepository[K, T])(nil).GetByKey), ctx, key)
}

// Save mocks base method.
func (m *MockRepository[K, T]) Save(ctx context.Context, v *T) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, v)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockRepositoryMockRecorder[K, T]) Save(ctx, v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockRepository[K, T])(nil).Save), ctx, v)
}

// MockWriteRepository is a mock of WriteRepository interface.
type MockWriteRepository[K comparable, T any] struct {
	ctrl     *gomock.Controller
	recorder *MockWriteRepositoryMockRecorder[K, T]
	isgomock struct{}
}

// MockWriteRepositoryMockRecorder is the mock recorder for MockWriteRepository.
type MockWriteRepositoryMockRecorder[K comparable, T any] struct {
	mock *MockWriteRepository[K, T]
}

// NewMockWriteRepository creates a new mock instance.
func NewMockWriteRepository[K comparable, T any](ctrl *gomock.Controller) *MockWriteRepository[K, T] {
	mock := &MockWriteRepository[K, T]{ctrl: ctrl}
	mock.recorder = &MockWriteRepositoryMockRecorder[K, T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWriteRepository[K, T]) EXPECT() *MockWriteRepositoryMockRecorder[K, T] {
	return m.recorder
}

// Delete mocks base method.
func (m *MockWriteRepository[K, T]) Delete(ctx context.Context, v *T) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, v)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockWriteRepositoryMockRecorder[K, T]) Delete(ctx, v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockWriteRepository[K, T])(nil).Delete), ctx, v)
}

// DeleteByKey mocks base method.
func (m *MockWriteRepository[K, T]) DeleteByKey(ctx context.Context, key K) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByKey", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByKey indicates an expected call of DeleteByKey.
func (mr *MockWriteRepositoryMockRecorder[K, T]) DeleteByKey(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByKey", reflect.TypeOf((*MockWriteRepository[K, T])(nil).DeleteByKey), ctx, key)
}

// Save mocks base method.
func (m *MockWriteRepository[K, T]) Save(ctx context.Context, v *T) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, v)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockWriteRepositoryMockRecorder[K, T]) Save(ctx, v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockWriteRepository[K, T])(nil).Save), ctx, v)
}

// MockWriteBatchRepository is a mock of WriteBatchRepository interface.
type MockWriteBatchRepository[K comparable, T any] struct {
	ctrl     *gomock.Controller
	recorder *MockWriteBatchRepositoryMockRecorder[K, T]
	isgomock struct{}
}

// MockWriteBatchRepositoryMockRecorder is the mock recorder for MockWriteBatchRepository.
type MockWriteBatchRepositoryMockRecorder[K comparable, T any] struct {
	mock *MockWriteBatchRepository[K, T]
}

// NewMockWriteBatchRepository creates a new mock instance.
func NewMockWriteBatchRepository[K comparable, T any](ctrl *gomock.Controller) *MockWriteBatchRepository[K, T] {
	mock := &MockWriteBatchRepository[K, T]{ctrl: ctrl}
	mock.recorder = &MockWriteBatchRepositoryMockRecorder[K, T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWriteBatchRepository[K, T]) EXPECT() *MockWriteBatchRepositoryMockRecorder[K, T] {
	return m.recorder
}

// DeleteAll mocks base method.
func (m *MockWriteBatchRepository[K, T]) DeleteAll(ctx context.Context, v ...T) ([]K, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range v {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteAll", varargs...)
	ret0, _ := ret[0].([]K)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteAll indicates an expected call of DeleteAll.
func (mr *MockWriteBatchRepositoryMockRecorder[K, T]) DeleteAll(ctx any, v ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, v...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAll", reflect.TypeOf((*MockWriteBatchRepository[K, T])(nil).DeleteAll), varargs...)
}

// DeleteByKeys mocks base method.
func (m *MockWriteBatchRepository[K, T]) DeleteByKeys(ctx context.Context, keys ...K) ([]K, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range keys {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteByKeys", varargs...)
	ret0, _ := ret[0].([]K)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteByKeys indicates an expected call of DeleteByKeys.
func (mr *MockWriteBatchRepositoryMockRecorder[K, T]) DeleteByKeys(ctx any, keys ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, keys...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByKeys", reflect.TypeOf((*MockWriteBatchRepository[K, T])(nil).DeleteByKeys), varargs...)
}

// SaveAll mocks base method.
func (m *MockWriteBatchRepository[K, T]) SaveAll(ctx context.Context, v ...T) ([]K, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range v {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SaveAll", varargs...)
	ret0, _ := ret[0].([]K)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveAll indicates an expected call of SaveAll.
func (mr *MockWriteBatchRepositoryMockRecorder[K, T]) SaveAll(ctx any, v ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, v...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveAll", reflect.TypeOf((*MockWriteBatchRepository[K, T])(nil).SaveAll), varargs...)
}

// MockReadRepository is a mock of ReadRepository interface.
type MockReadRepository[K comparable, T any] struct {
	ctrl     *gomock.Controller
	recorder *MockReadRepositoryMockRecorder[K, T]
	isgomock struct{}
}

// MockReadRepositoryMockRecorder is the mock recorder for MockReadRepository.
type MockReadRepositoryMockRecorder[K comparable, T any] struct {
	mock *MockReadRepository[K, T]
}

// NewMockReadRepository creates a new mock instance.
func NewMockReadRepository[K comparable, T any](ctrl *gomock.Controller) *MockReadRepository[K, T] {
	mock := &MockReadRepository[K, T]{ctrl: ctrl}
	mock.recorder = &MockReadRepositoryMockRecorder[K, T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReadRepository[K, T]) EXPECT() *MockReadRepositoryMockRecorder[K, T] {
	return m.recorder
}

// GetByKey mocks base method.
func (m *MockReadRepository[K, T]) GetByKey(ctx context.Context, key K) (*T, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByKey", ctx, key)
	ret0, _ := ret[0].(*T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByKey indicates an expected call of GetByKey.
func (mr *MockReadRepositoryMockRecorder[K, T]) GetByKey(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByKey", reflect.TypeOf((*MockReadRepository[K, T])(nil).GetByKey), ctx, key)
}
