// Code generated by MockGen. DO NOT EDIT.
// Source: background.go
//
// Generated by this command:
//
//	mockgen -source=background.go -destination=proctest/background_mock.go -package=proctest
//

// Package proctest is a generated GoMock package.
package proctest

import (
	reflect "reflect"

	proc "github.com/bosonicalcom/bedrock-go/proc"
	gomock "go.uber.org/mock/gomock"
)

// MockBackgroundFactory is a mock of BackgroundFactory interface.
type MockBackgroundFactory struct {
	ctrl     *gomock.Controller
	recorder *MockBackgroundFactoryMockRecorder
	isgomock struct{}
}

// MockBackgroundFactoryMockRecorder is the mock recorder for MockBackgroundFactory.
type MockBackgroundFactoryMockRecorder struct {
	mock *MockBackgroundFactory
}

// NewMockBackgroundFactory creates a new mock instance.
func NewMockBackgroundFactory(ctrl *gomock.Controller) *MockBackgroundFactory {
	mock := &MockBackgroundFactory{ctrl: ctrl}
	mock.recorder = &MockBackgroundFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBackgroundFactory) EXPECT() *MockBackgroundFactoryMockRecorder {
	return m.recorder
}

// BackgroundProcess mocks base method.
func (m *MockBackgroundFactory) BackgroundProcess() proc.BackgroundProcess {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BackgroundProcess")
	ret0, _ := ret[0].(proc.BackgroundProcess)
	return ret0
}

// BackgroundProcess indicates an expected call of BackgroundProcess.
func (mr *MockBackgroundFactoryMockRecorder) BackgroundProcess() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BackgroundProcess", reflect.TypeOf((*MockBackgroundFactory)(nil).BackgroundProcess))
}
