name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened]

jobs:
  ci:
    uses: bosonicalcom/github-workflows/.github/workflows/ci-go.yml@master
    secrets: inherit
    with:
      go-version: "1.26.1"
      docker-build: false
